name: Build

on:
  pull_request:
    branches:
      - "*"

jobs:
  build-v2:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.3.0
        with:
          xcode-version: latest-stable
      - name: Set variables
        run: |
          HASH=$(cat SNAPSHOT_HASH)
          echo "SNAPSHOT_HASH=$HASH" >> $GITHUB_ENV
      - name: Install tools
        run: |
          brew install ninja libusbmuxd ideviceinstaller ios-deploy python@3.11
          sudo rm -rf /usr/local/bin/python3
          sudo ln -s /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 /usr/local/bin/python3
          python3 --version
          which python3
          


          
